# Generated by Django 2.0.6 on 2020-05-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.SmallIntegerField(null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'test',
                'verbose_name': '测试',
                'verbose_name_plural': '测试',
            },
        ),
    ]
