# Generated by Django 2.0.6 on 2020-05-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_order_user01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='年级名')),
                ('is_del', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='学校名')),
                ('is_del', models.IntegerField(default=0)),
                ('grade', models.ManyToManyField(to='testapp.Grade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('updated_time', models.DateField(auto_now=True, null=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='学生名')),
                ('is_del', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ManyToManyField(to='testapp.Student'),
        ),
    ]
